# flake8: noqa
# fmt: off
# mypy: disable-error-code="no-any-return, no-untyped-call, misc, type-arg"
# This file was automatically generated by algokit-client-generator.
# DO NOT MODIFY IT BY HAND.
# requires: algokit-utils@^3.0.0

from dataclasses import dataclass, asdict, replace
from typing import (
    Any,
    Callable,
    Optional,
    Protocol,
    Union,
    overload,
    Generic,
    Tuple,
    TypedDict,
    runtime_checkable,
    cast,
    Literal,
)
import algosdk
from algosdk.transaction import OnComplete
from algokit_utils.applications import AppFactoryCreateParams, AppFactoryCreateMethodCallResult, AppFactoryCreateWithSendParams, AppFactoryCreateMethodCallParams
from algokit_utils.applications import (
    AppClient,
    AppClientBareCallWithSendParams,
    AppClientMethodCallWithSendParams,
    AppClientMethodCallWithCompilationAndSendParams,
    AppClientMethodCallParams,
    AppClientParams,
    AppFactory,
    AppFactoryParams,
    Arc56Contract,
    AppClientBareCallWithCompilationAndSendParams,
    AppClientBareCallParams,
    AppClientCreateSchema,
    BaseOnCompleteParams,
    AppClientMethodCallParams,
    AppClientBareCallParams,
    AppClientBareCallCreateParams,
    AppClientMethodCallCreateParams,
    BaseAppClientMethodCallParams,
)
from algokit_utils.transactions import SendAppCreateTransactionResult, AppCallParams, AppCreateParams, AppDeleteParams, AppUpdateParams, AppCreateMethodCallParams
from algosdk.atomic_transaction_composer import TransactionWithSigner
from algokit_utils.applications.abi import ABIReturn, ABIStruct, ABIValue
from algokit_utils.applications.app_deployer import AppLookup, OnSchemaBreak, OnUpdate
from algokit_utils.applications.app_factory import (
    AppFactoryDeployResponse,
    TypedAppFactoryProtocol,
)
from algokit_utils.models import AlgoAmount, BoxIdentifier, BoxReference
from algokit_utils.models.state import TealTemplateParams
from algokit_utils.protocols import AlgorandClientProtocol
from algokit_utils.transactions import (
    AppCallMethodCallParams,
    AppCallParams,
    SendAppUpdateTransactionResult,
                      
    SendAppTransactionResult,
    SendAtomicTransactionComposerResults,
    TransactionComposer,
)
from algokit_utils.transactions.transaction_composer import BuiltTransactions
from algosdk.atomic_transaction_composer import TransactionSigner
from algosdk.source_map import SourceMap
from algosdk.transaction import Transaction
from algosdk.v2client.models import SimulateTraceConfig

_APP_SPEC_JSON = r"""{
    "arcs": [],
    "bareActions": {
        "call": [
            "DeleteApplication",
            "UpdateApplication"
        ],
        "create": [
            "NoOp"
        ]
    },
    "methods": [],
    "name": "MinimalApp",
    "state": {
        "keys": {
            "box": {},
            "global": {},
            "local": {}
        },
        "maps": {
            "box": {},
            "global": {},
            "local": {}
        },
        "schema": {
            "global": {
                "bytes": 0,
                "ints": 0
            },
            "local": {
                "bytes": 0,
                "ints": 0
            }
        }
    },
    "structs": {},
    "desc": "An app that has no abi methods",
    "source": {
        "approval": "I3ByYWdtYSB2ZXJzaW9uIDgKaW50Y2Jsb2NrIDAgMQp0eG4gTnVtQXBwQXJncwppbnRjXzAgLy8gMAo9PQpibnogbWFpbl9sMgplcnIKbWFpbl9sMjoKdHhuIE9uQ29tcGxldGlvbgppbnRjXzAgLy8gTm9PcAo9PQpibnogbWFpbl9sOAp0eG4gT25Db21wbGV0aW9uCnB1c2hpbnQgNCAvLyBVcGRhdGVBcHBsaWNhdGlvbgo9PQpibnogbWFpbl9sNwp0eG4gT25Db21wbGV0aW9uCnB1c2hpbnQgNSAvLyBEZWxldGVBcHBsaWNhdGlvbgo9PQpibnogbWFpbl9sNgplcnIKbWFpbl9sNjoKdHhuIEFwcGxpY2F0aW9uSUQKaW50Y18wIC8vIDAKIT0KYXNzZXJ0CmNhbGxzdWIgZGVsZXRlXzEKaW50Y18xIC8vIDEKcmV0dXJuCm1haW5fbDc6CnR4biBBcHBsaWNhdGlvbklECmludGNfMCAvLyAwCiE9CmFzc2VydApjYWxsc3ViIHVwZGF0ZV8wCmludGNfMSAvLyAxCnJldHVybgptYWluX2w4Ogp0eG4gQXBwbGljYXRpb25JRAppbnRjXzAgLy8gMAo9PQphc3NlcnQKaW50Y18xIC8vIDEKcmV0dXJuCgovLyB1cGRhdGUKdXBkYXRlXzA6CnByb3RvIDAgMAp0eG4gU2VuZGVyCmdsb2JhbCBDcmVhdG9yQWRkcmVzcwo9PQovLyB1bmF1dGhvcml6ZWQKYXNzZXJ0CnB1c2hpbnQgVE1QTF9VUERBVEFCTEUgLy8gVE1QTF9VUERBVEFCTEUKLy8gQ2hlY2sgYXBwIGlzIHVwZGF0YWJsZQphc3NlcnQKcmV0c3ViCgovLyBkZWxldGUKZGVsZXRlXzE6CnByb3RvIDAgMAp0eG4gU2VuZGVyCmdsb2JhbCBDcmVhdG9yQWRkcmVzcwo9PQovLyB1bmF1dGhvcml6ZWQKYXNzZXJ0CnB1c2hpbnQgVE1QTF9ERUxFVEFCTEUgLy8gVE1QTF9ERUxFVEFCTEUKLy8gQ2hlY2sgYXBwIGlzIGRlbGV0YWJsZQphc3NlcnQKcmV0c3Vi",
        "clear": "I3ByYWdtYSB2ZXJzaW9uIDgKcHVzaGludCAwIC8vIDAKcmV0dXJu"
    }
}"""
APP_SPEC = Arc56Contract.from_json(_APP_SPEC_JSON)


class _MinimalAppUpdate:
    def __init__(self, app_client: AppClient):
        self.app_client = app_client

    def bare(self, params: AppClientBareCallWithCompilationAndSendParams | None = None) -> AppUpdateParams:
        return self.app_client.params.bare.update(params)


class _MinimalAppDelete:
    def __init__(self, app_client: AppClient):
        self.app_client = app_client

    def bare(self, params: AppClientBareCallWithSendParams | None = None) -> AppCallParams:
        return self.app_client.params.bare.delete(params)


class MinimalAppParams:
    def __init__(self, app_client: AppClient):
        self.app_client = app_client
    @property
    def update(self) -> "_MinimalAppUpdate":
        return _MinimalAppUpdate(self.app_client)

    @property
    def delete(self) -> "_MinimalAppDelete":
        return _MinimalAppDelete(self.app_client)

    def clear_state(self, params: AppClientBareCallWithSendParams | None = None) -> AppCallParams:
        return self.app_client.params.bare.clear_state(params)


class _MinimalAppUpdateTransaction:
    def __init__(self, app_client: AppClient):
        self.app_client = app_client

    def bare(self, params: AppClientBareCallWithCompilationAndSendParams | None = None) -> Transaction:
        return self.app_client.create_transaction.bare.update(params)


class _MinimalAppDeleteTransaction:
    def __init__(self, app_client: AppClient):
        self.app_client = app_client

    def bare(self, params: AppClientBareCallWithSendParams | None = None) -> Transaction:
        return self.app_client.create_transaction.bare.delete(params)


class MinimalAppCreateTransactionParams:
    def __init__(self, app_client: AppClient):
        self.app_client = app_client
    @property
    def update(self) -> "_MinimalAppUpdateTransaction":
        return _MinimalAppUpdateTransaction(self.app_client)

    @property
    def delete(self) -> "_MinimalAppDeleteTransaction":
        return _MinimalAppDeleteTransaction(self.app_client)

    def clear_state(self, params: AppClientBareCallWithSendParams | None = None) -> Transaction:
        return self.app_client.create_transaction.bare.clear_state(params)


class _MinimalAppUpdateSend:
    def __init__(self, app_client: AppClient):
        self.app_client = app_client

    def bare(self, params: AppClientBareCallWithCompilationAndSendParams | None = None) -> SendAppTransactionResult:
        return self.app_client.send.bare.update(params)


class _MinimalAppDeleteSend:
    def __init__(self, app_client: AppClient):
        self.app_client = app_client

    def bare(self, params: AppClientBareCallWithSendParams | None = None) -> SendAppTransactionResult:
        return self.app_client.send.bare.delete(params)


class MinimalAppSend:
    def __init__(self, app_client: AppClient):
        self.app_client = app_client
    @property
    def update(self) -> "_MinimalAppUpdateSend":
        return _MinimalAppUpdateSend(self.app_client)

    @property
    def delete(self) -> "_MinimalAppDeleteSend":
        return _MinimalAppDeleteSend(self.app_client)

    def clear_state(self, params: AppClientBareCallWithSendParams | None = None) -> SendAppTransactionResult[ABIReturn]:
        return self.app_client.send.bare.clear_state(params)


class MinimalAppState:
    """Methods to access state for the current MinimalApp app"""

    def __init__(self, app_client: AppClient):
        self.app_client = app_client

class MinimalAppClient:
    """Client for interacting with MinimalApp smart contract"""

    @overload
    def __init__(self, app_client: AppClient) -> None: ...
    
    @overload
    def __init__(
        self,
        *,
        algorand: AlgorandClientProtocol,
        app_id: int,
        app_name: str | None = None,
        default_sender: str | bytes | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
    ) -> None: ...

    def __init__(
        self,
        app_client: AppClient | None = None,
        *,
        algorand: AlgorandClientProtocol | None = None,
        app_id: int | None = None,
        app_name: str | None = None,
        default_sender: str | bytes | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
    ) -> None:
        if app_client:
            self.app_client = app_client
        elif algorand and app_id:
            self.app_client = AppClient(
                AppClientParams(
                    algorand=algorand,
                    app_spec=APP_SPEC,
                    app_id=app_id,
                    app_name=app_name,
                    default_sender=default_sender,
                    default_signer=default_signer,
                    approval_source_map=approval_source_map,
                    clear_source_map=clear_source_map,
                )
            )
        else:
            raise ValueError("Either app_client or algorand and app_id must be provided")
    
        self.params = MinimalAppParams(self.app_client)
        self.create_transaction = MinimalAppCreateTransactionParams(self.app_client)
        self.send = MinimalAppSend(self.app_client)
        self.state = MinimalAppState(self.app_client)

    @staticmethod
    def from_creator_and_name(
        creator_address: str,
        app_name: str,
        algorand: AlgorandClientProtocol,
        default_sender: str | bytes | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
        ignore_cache: bool | None = None,
        app_lookup_cache: AppLookup | None = None,
    ) -> "MinimalAppClient":
        return MinimalAppClient(
            AppClient.from_creator_and_name(
                creator_address=creator_address,
                app_name=app_name,
                app_spec=APP_SPEC,
                algorand=algorand,
                default_sender=default_sender,
                default_signer=default_signer,
                approval_source_map=approval_source_map,
                clear_source_map=clear_source_map,
                ignore_cache=ignore_cache,
                app_lookup_cache=app_lookup_cache,
            )
        )
    
    @staticmethod
    def from_network(
        algorand: AlgorandClientProtocol,
        app_name: str | None = None,
        default_sender: str | bytes | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
    ) -> "MinimalAppClient":
        return MinimalAppClient(
            AppClient.from_network(
                app_spec=APP_SPEC,
                algorand=algorand,
                app_name=app_name,
                default_sender=default_sender,
                default_signer=default_signer,
                approval_source_map=approval_source_map,
                clear_source_map=clear_source_map,
            )
        )

    @property
    def app_id(self) -> int:
        return self.app_client.app_id
    
    @property
    def app_address(self) -> str:
        return self.app_client.app_address
    
    @property
    def app_name(self) -> str:
        return self.app_client.app_name
    
    @property
    def app_spec(self) -> Arc56Contract:
        return self.app_client.app_spec
    
    @property
    def algorand(self) -> AlgorandClientProtocol:
        return self.app_client.algorand

    def clone(
        self,
        app_name: str | None = None,
        default_sender: str | bytes | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
    ) -> "MinimalAppClient":
        return MinimalAppClient(
            self.app_client.clone(
                app_name=app_name,
                default_sender=default_sender,
                default_signer=default_signer,
                approval_source_map=approval_source_map,
                clear_source_map=clear_source_map,
            )
        )

    def new_group(self) -> "MinimalAppComposer":
        return MinimalAppComposer(self)

    def decode_return_value(
        self,
        method: str,
        return_value: ABIReturn | None
    ) -> ABIValue | ABIStruct | None:
        if return_value is None:
            return None
    
        arc56_method = self.app_spec.get_arc56_method(method)
        return return_value.get_arc56_value(arc56_method, self.app_spec.structs)


@dataclass(frozen=True)
class MinimalAppBareCallCreateParams(AppClientCreateSchema, AppClientBareCallParams, BaseOnCompleteParams[Literal[OnComplete.NoOpOC]]):
    """Parameters for creating MinimalApp contract using bare calls"""

    def to_algokit_utils_params(self) -> AppClientBareCallCreateParams:
        return AppClientBareCallCreateParams(**self.__dict__)

@dataclass(frozen=True)
class MinimalAppBareCallUpdateParams(AppClientBareCallParams):
    """Parameters for calling MinimalApp contract using bare calls"""

    def to_algokit_utils_params(self) -> AppClientBareCallParams:
        return AppClientBareCallParams(**self.__dict__)

@dataclass(frozen=True)
class MinimalAppBareCallDeleteParams(AppClientBareCallParams):
    """Parameters for calling MinimalApp contract using bare calls"""

    def to_algokit_utils_params(self) -> AppClientBareCallParams:
        return AppClientBareCallParams(**self.__dict__)

class MinimalAppFactory(TypedAppFactoryProtocol):
    """Factory for deploying and managing MinimalAppClient smart contracts"""

    def __init__(
        self,
        algorand: AlgorandClientProtocol,
        *,
        app_name: str | None = None,
        default_sender: str | bytes | None = None,
        default_signer: TransactionSigner | None = None,
        version: str | None = None,
        updatable: bool | None = None,
        deletable: bool | None = None,
        deploy_time_params: TealTemplateParams | None = None,
    ):
        self.app_factory = AppFactory(
            params=AppFactoryParams(
                algorand=algorand,
                app_spec=APP_SPEC,
                app_name=app_name,
                default_sender=default_sender,
                default_signer=default_signer,
                version=version,
                updatable=updatable,
                deletable=deletable,
                deploy_time_params=deploy_time_params,
            )
        )
        self.params = MinimalAppFactoryParams(self.app_factory)
        self.create_transaction = MinimalAppFactoryCreateTransaction(self.app_factory)
        self.send = MinimalAppFactorySend(self.app_factory)

    @property
    def app_name(self) -> str:
        return self.app_factory.app_name

    @property
    def app_spec(self) -> Arc56Contract:
        return self.app_factory.app_spec

    @property
    def algorand(self) -> AlgorandClientProtocol:
        return self.app_factory.algorand

    def deploy(
        self,
        *,
        deploy_time_params: TealTemplateParams | None = None,
        on_update: OnUpdate = OnUpdate.Fail,
        on_schema_break: OnSchemaBreak = OnSchemaBreak.Fail,
        create_params: MinimalAppBareCallCreateParams | None = None,
        update_params: MinimalAppBareCallUpdateParams | None = None,
        delete_params: MinimalAppBareCallDeleteParams | None = None,
        existing_deployments: AppLookup | None = None,
        ignore_cache: bool = False,
        updatable: bool | None = None,
        deletable: bool | None = None,
        app_name: str | None = None,
        max_rounds_to_wait: int | None = None,
        suppress_log: bool = False,
        populate_app_call_resources: bool = False,
    ) -> tuple[MinimalAppClient, AppFactoryDeployResponse]:
        deploy_response = self.app_factory.deploy(
            deploy_time_params=deploy_time_params,
            on_update=on_update,
            on_schema_break=on_schema_break,
            create_params=create_params.to_algokit_utils_params() if create_params else None,
            update_params=update_params.to_algokit_utils_params() if update_params else None,
            delete_params=delete_params.to_algokit_utils_params() if delete_params else None,
            existing_deployments=existing_deployments,
            ignore_cache=ignore_cache,
            updatable=updatable,
            deletable=deletable,
            app_name=app_name,
            max_rounds_to_wait=max_rounds_to_wait,
            suppress_log=suppress_log,
            populate_app_call_resources=populate_app_call_resources,
        )

        return MinimalAppClient(deploy_response[0]), deploy_response[1]

    def get_app_client_by_creator_and_name(
        self,
        creator_address: str,
        app_name: str,
        default_sender: str | bytes | None = None,
        default_signer: TransactionSigner | None = None,
        ignore_cache: bool | None = None,
        app_lookup_cache: AppLookup | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
    ) -> MinimalAppClient:
        """Get an app client by creator address and name"""
        return MinimalAppClient(
            self.app_factory.get_app_client_by_creator_and_name(
                creator_address,
                app_name,
                default_sender,
                default_signer,
                ignore_cache,
                app_lookup_cache,
                approval_source_map,
                clear_source_map,
            )
        )

    def get_app_client_by_id(
        self,
        app_id: int,
        app_name: str | None = None,
        default_sender: str | bytes | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
    ) -> MinimalAppClient:
        """Get an app client by app ID"""
        return MinimalAppClient(
            self.app_factory.get_app_client_by_id(
                app_id,
                app_name,
                default_sender,
                default_signer,
                approval_source_map,
                clear_source_map,
            )
        )


class MinimalAppFactoryParams:
    """Parameters for creating transactions for MinimalApp contract"""

    def __init__(self, app_factory: AppFactory):
        self.app_factory = app_factory
        self.create = MinimalAppFactoryCreateParams(app_factory)
        self.deploy_update = MinimalAppFactoryUpdateParams(app_factory)
        self.deploy_delete = MinimalAppFactoryDeleteParams(app_factory)

class MinimalAppFactoryCreateParams:
    """Parameters for 'create' operations of MinimalApp contract"""

    def __init__(self, app_factory: AppFactory):
        self.app_factory = app_factory

    def bare(
        self,
        *,
        on_complete: (Literal[
                OnComplete.NoOpOC,
                OnComplete.UpdateApplicationOC,
                OnComplete.DeleteApplicationOC,
                OnComplete.OptInOC,
                OnComplete.CloseOutOC,
            ] | None) = None,
        **kwargs
    ) -> AppCreateParams:
        """Creates an instance using a bare call"""
        return self.app_factory.params.bare.create(
            AppFactoryCreateParams(on_complete=on_complete, **kwargs)
        )

class MinimalAppFactoryUpdateParams:
    """Parameters for 'update' operations of MinimalApp contract"""

    def __init__(self, app_factory: AppFactory):
        self.app_factory = app_factory

    def bare(
        self,
        *,
        on_complete: (Literal[
                OnComplete.NoOpOC,
                OnComplete.UpdateApplicationOC,
                OnComplete.DeleteApplicationOC,
                OnComplete.OptInOC,
                OnComplete.CloseOutOC,
            ] | None) = None,
        **kwargs
    ) -> AppUpdateParams:
        """Updates an instance using a bare call"""
        return self.app_factory.params.bare.deploy_update(
            AppFactoryCreateParams(on_complete=on_complete, **kwargs)
        )

class MinimalAppFactoryDeleteParams:
    """Parameters for 'delete' operations of MinimalApp contract"""

    def __init__(self, app_factory: AppFactory):
        self.app_factory = app_factory

    def bare(
        self,
        *,
        on_complete: (Literal[
                OnComplete.NoOpOC,
                OnComplete.UpdateApplicationOC,
                OnComplete.DeleteApplicationOC,
                OnComplete.OptInOC,
                OnComplete.CloseOutOC,
            ] | None) = None,
        **kwargs
    ) -> AppDeleteParams:
        """Deletes an instance using a bare call"""
        return self.app_factory.params.bare.deploy_delete(
            AppFactoryCreateParams(on_complete=on_complete, **kwargs)
        )


class MinimalAppFactoryCreateTransaction:
    """Create transactions for MinimalApp contract"""

    def __init__(self, app_factory: AppFactory):
        self.app_factory = app_factory
        self.create = MinimalAppFactoryCreateTransactionCreate(app_factory)

class MinimalAppFactoryCreateTransactionCreate:
    """Create new instances of MinimalApp contract"""

    def __init__(self, app_factory: AppFactory):
        self.app_factory = app_factory

    def bare(
        self,
        *,
        on_complete: (Literal[
                OnComplete.NoOpOC,
                OnComplete.UpdateApplicationOC,
                OnComplete.DeleteApplicationOC,
                OnComplete.OptInOC,
                OnComplete.CloseOutOC,
            ] | None) = None,
        **kwargs
    ) -> Transaction:
        """Creates a new instance using a bare call"""
        return self.app_factory.create_transaction.bare.create(
            AppFactoryCreateParams(on_complete=on_complete, **kwargs)
        )


class MinimalAppFactorySend:
    """Send calls to MinimalApp contract"""

    def __init__(self, app_factory: AppFactory):
        self.app_factory = app_factory
        self.create = MinimalAppFactorySendCreate(app_factory)


class MinimalAppFactorySendCreate:
    """Send create calls to MinimalApp contract"""

    def __init__(self, app_factory: AppFactory):
        self.app_factory = app_factory

    def bare(
        self,
        *,
        on_complete: (Literal[
                OnComplete.NoOpOC,
                OnComplete.UpdateApplicationOC,
                OnComplete.DeleteApplicationOC,
                OnComplete.OptInOC,
                OnComplete.CloseOutOC,
            ] | None) = None,
        **kwargs
    ) -> tuple[MinimalAppClient, SendAppCreateTransactionResult]:
        """Creates a new instance using a bare call"""
        result = self.app_factory.send.bare.create(
            AppFactoryCreateWithSendParams(on_complete=on_complete, **kwargs)
        )
        return MinimalAppClient(result[0]), result[1]


class _MinimalAppUpdateComposer:
    def __init__(self, composer: "MinimalAppComposer"):
        self.composer = composer


class _MinimalAppDeleteComposer:
    def __init__(self, composer: "MinimalAppComposer"):
        self.composer = composer


class MinimalAppComposer:
    """Composer for creating transaction groups for MinimalApp contract calls"""

    def __init__(self, client: "MinimalAppClient"):
        self.client = client
        self._composer = client.algorand.new_group()
        self._result_mappers: list[Optional[Callable[[Optional[ABIReturn]], Any]]] = []

    @property
    def update(self) -> "_MinimalAppUpdateComposer":
        return _MinimalAppUpdateComposer(self)

    @property
    def delete(self) -> "_MinimalAppDeleteComposer":
        return _MinimalAppDeleteComposer(self)

    def clear_state(
        self,
        *,
        account_references: Optional[list[str]] = None,
        app_references: Optional[list[int]] = None,
        asset_references: Optional[list[int]] = None,
        box_references: Optional[list[Union[BoxReference, BoxIdentifier]]] = None,
        extra_fee: Optional[AlgoAmount] = None,
        first_valid_round: Optional[int] = None,
        lease: Optional[bytes] = None,
        max_fee: Optional[AlgoAmount] = None,
        note: Optional[bytes] = None,
        rekey_to: Optional[str] = None,
        sender: Optional[str] = None,
        signer: Optional[TransactionSigner] = None,
        static_fee: Optional[AlgoAmount] = None,
        validity_window: Optional[int] = None,
        last_valid_round: Optional[int] = None,
    ) -> "MinimalAppComposer":
        self._composer.add_app_call(
            self.client.params.clear_state(
                AppClientBareCallWithSendParams(
                    account_references=account_references,
                    app_references=app_references,
                    asset_references=asset_references,
                    box_references=box_references,
                    extra_fee=extra_fee,
                    first_valid_round=first_valid_round,
                    lease=lease,
                    max_fee=max_fee,
                    note=note,
                    rekey_to=rekey_to,
                    sender=sender,
                    signer=signer,
                    static_fee=static_fee,
                    validity_window=validity_window,
                    last_valid_round=last_valid_round,
                )
            )
        )
        return self
    
    def add_transaction(
        self, txn: Transaction, signer: Optional[TransactionSigner] = None
    ) -> "MinimalAppComposer":
        self._composer.add_transaction(txn, signer)
        return self
    
    def composer(self) -> TransactionComposer:
        return self._composer
    
    def simulate(
        self,
        allow_more_logs: bool | None = None,
        allow_empty_signatures: bool | None = None,
        allow_unnamed_resources: bool | None = None,
        extra_opcode_budget: int | None = None,
        exec_trace_config: SimulateTraceConfig | None = None,
        simulation_round: int | None = None,
        skip_signatures: int | None = None,
    ) -> SendAtomicTransactionComposerResults:
        return self._composer.simulate(
            allow_more_logs=allow_more_logs,
            allow_empty_signatures=allow_empty_signatures,
            allow_unnamed_resources=allow_unnamed_resources,
            extra_opcode_budget=extra_opcode_budget,
            exec_trace_config=exec_trace_config,
            simulation_round=simulation_round,
            skip_signatures=skip_signatures,
        )
    
    def send(
        self,
        max_rounds_to_wait: int | None = None,
        suppress_log: bool | None = None,
        populate_app_call_resources: bool | None = None,
    ) -> SendAtomicTransactionComposerResults:
        return self._composer.send(
            max_rounds_to_wait=max_rounds_to_wait,
            suppress_log=suppress_log,
            populate_app_call_resources=populate_app_call_resources,
        )
