version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps)'
    groups:
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'
