# flake8: noqa
# fmt: off
# mypy: disable-error-code="no-any-return, no-untyped-call, misc, type-arg"
# This file was automatically generated by algokit-client-generator.
# DO NOT MODIFY IT BY HAND.
# requires: algokit-utils@^3.0.0

# common
import dataclasses
import typing
# algokit utils
from algokit_abi import arc56
import algokit_utils
from algokit_utils import AlgorandClient as _AlgoKitAlgorandClient
from algokit_algosdk.source_map import SourceMap
from algokit_transact.models.common import OnApplicationComplete
from algokit_transact.models.transaction import Transaction
from algokit_utils.protocols.signer import TransactionSigner
from algokit_algod_client.models import SimulateTraceConfig


@dataclasses.dataclass(frozen=True, kw_only=True)
class HelloArgs:
    """Dataclass for hello arguments"""
    name: str

    @property
    def abi_method_signature(self) -> str:
        return "hello(string)string"

@dataclasses.dataclass(frozen=True, kw_only=True)
class HelloWorldCheckArgs:
    """Dataclass for hello_world_check arguments"""
    name: str

    @property
    def abi_method_signature(self) -> str:
        return "hello_world_check(string)void"


class HelloWorldParams:
    def __init__(self, app_client: algokit_utils.AppClient):
        self.app_client = app_client

    def hello(
        self,
        args: tuple[str] | HelloArgs,
        params: algokit_utils.CommonAppCallParams | None = None
    ) -> algokit_utils.AppCallMethodCallParams:
        params = params or algokit_utils.CommonAppCallParams()
        return self.app_client.params.call(_extend(
            algokit_utils.AppClientMethodCallParams,
            params,
            method="hello(string)string",
            args=_unpack_args(args),
        ))

    def hello_world_check(
        self,
        args: tuple[str] | HelloWorldCheckArgs,
        params: algokit_utils.CommonAppCallParams | None = None
    ) -> algokit_utils.AppCallMethodCallParams:
        params = params or algokit_utils.CommonAppCallParams()
        return self.app_client.params.call(_extend(
            algokit_utils.AppClientMethodCallParams,
            params,
            method="hello_world_check(string)void",
            args=_unpack_args(args),
        ))

    def clear_state(
        self,
        params: algokit_utils.AppClientBareCallParams | None = None,
        
    ) -> algokit_utils.AppCallParams:
        return self.app_client.params.bare.clear_state(
            params,
            
        )


class HelloWorldCreateTransactionParams:
    def __init__(self, app_client: algokit_utils.AppClient):
        self.app_client = app_client

    def hello(
        self,
        args: tuple[str] | HelloArgs,
        params: algokit_utils.CommonAppCallParams | None = None
    ) -> algokit_utils.BuiltTransactions:
        params = params or algokit_utils.CommonAppCallParams()
        return self.app_client.create_transaction.call(_extend(
            algokit_utils.AppClientMethodCallParams,
            params,
            method="hello(string)string",
            args=_unpack_args(args),
        ))

    def hello_world_check(
        self,
        args: tuple[str] | HelloWorldCheckArgs,
        params: algokit_utils.CommonAppCallParams | None = None
    ) -> algokit_utils.BuiltTransactions:
        params = params or algokit_utils.CommonAppCallParams()
        return self.app_client.create_transaction.call(_extend(
            algokit_utils.AppClientMethodCallParams,
            params,
            method="hello_world_check(string)void",
            args=_unpack_args(args),
        ))

    def clear_state(
        self,
        params: algokit_utils.AppClientBareCallParams | None = None,
        
    ) -> Transaction:
        return self.app_client.create_transaction.bare.clear_state(
            params,
            
        )


class HelloWorldSend:
    def __init__(self, app_client: algokit_utils.AppClient):
        self.app_client = app_client

    def hello(
        self,
        args: tuple[str] | HelloArgs,
        params: algokit_utils.CommonAppCallParams | None = None,
        send_params: algokit_utils.SendParams | None = None
    ) -> algokit_utils.SendAppTransactionResult[str]:
        params = params or algokit_utils.CommonAppCallParams()
        response = self.app_client.send.call(_extend(
            algokit_utils.AppClientMethodCallParams,
            params,
            method="hello(string)string",
            args=_unpack_args(args),
        ), send_params=send_params)
        return typing.cast(algokit_utils.SendAppTransactionResult[str], response)

    def hello_world_check(
        self,
        args: tuple[str] | HelloWorldCheckArgs,
        params: algokit_utils.CommonAppCallParams | None = None,
        send_params: algokit_utils.SendParams | None = None
    ) -> algokit_utils.SendAppTransactionResult[None]:
        params = params or algokit_utils.CommonAppCallParams()
        response = self.app_client.send.call(_extend(
            algokit_utils.AppClientMethodCallParams,
            params,
            method="hello_world_check(string)void",
            args=_unpack_args(args),
        ), send_params=send_params)
        return typing.cast(algokit_utils.SendAppTransactionResult[None], response)

    def clear_state(
        self,
        params: algokit_utils.AppClientBareCallParams | None = None,
        send_params: algokit_utils.SendParams | None = None
    ) -> algokit_utils.SendAppTransactionResult[algokit_utils.ABIReturn]:
        return self.app_client.send.bare.clear_state(
            params,
            send_params=send_params,
        )


class HelloWorldState:
    """Methods to access state for the current HelloWorld app"""

    def __init__(self, app_client: algokit_utils.AppClient):
        self.app_client = app_client

class HelloWorldClient:
    """Client for interacting with HelloWorld smart contract"""

    @typing.overload
    def __init__(self, app_client: algokit_utils.AppClient) -> None: ...
    
    @typing.overload
    def __init__(
        self,
        *,
        algorand: _AlgoKitAlgorandClient,
        app_id: int,
        app_name: str | None = None,
        default_sender: str | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
    ) -> None: ...

    def __init__(
        self,
        app_client: algokit_utils.AppClient | None = None,
        *,
        algorand: _AlgoKitAlgorandClient | None = None,
        app_id: int | None = None,
        app_name: str | None = None,
        default_sender: str | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
    ) -> None:
        if app_client:
            self.app_client = app_client
        elif algorand and app_id:
            self.app_client = algokit_utils.AppClient(
                algokit_utils.AppClientParams(
                    algorand=algorand,
                    app_spec=APP_SPEC,
                    app_id=app_id,
                    app_name=app_name,
                    default_sender=default_sender,
                    default_signer=default_signer,
                    approval_source_map=approval_source_map,
                    clear_source_map=clear_source_map,
                )
            )
        else:
            raise ValueError("Either app_client or algorand and app_id must be provided")
    
        self.params = HelloWorldParams(self.app_client)
        self.create_transaction = HelloWorldCreateTransactionParams(self.app_client)
        self.send = HelloWorldSend(self.app_client)
        self.state = HelloWorldState(self.app_client)

    @staticmethod
    def from_creator_and_name(
        creator_address: str,
        app_name: str,
        algorand: _AlgoKitAlgorandClient,
        default_sender: str | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
        ignore_cache: bool | None = None,
        app_lookup_cache: algokit_utils.ApplicationLookup | None = None,
    ) -> "HelloWorldClient":
        return HelloWorldClient(
            algokit_utils.AppClient.from_creator_and_name(
                creator_address=creator_address,
                app_name=app_name,
                app_spec=APP_SPEC,
                algorand=algorand,
                default_sender=default_sender,
                default_signer=default_signer,
                approval_source_map=approval_source_map,
                clear_source_map=clear_source_map,
                ignore_cache=ignore_cache,
                app_lookup_cache=app_lookup_cache,
            )
        )
    
    @staticmethod
    def from_network(
        algorand: _AlgoKitAlgorandClient,
        app_name: str | None = None,
        default_sender: str | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
    ) -> "HelloWorldClient":
        return HelloWorldClient(
            algokit_utils.AppClient.from_network(
                app_spec=APP_SPEC,
                algorand=algorand,
                app_name=app_name,
                default_sender=default_sender,
                default_signer=default_signer,
                approval_source_map=approval_source_map,
                clear_source_map=clear_source_map,
            )
        )

    @property
    def app_id(self) -> int:
        return self.app_client.app_id
    
    @property
    def app_address(self) -> str:
        return self.app_client.app_address
    
    @property
    def app_name(self) -> str:
        return self.app_client.app_name
    
    @property
    def app_spec(self) -> arc56.Arc56Contract:
        return self.app_client.app_spec
    
    @property
    def algorand(self) -> _AlgoKitAlgorandClient:
        return self.app_client.algorand

    def clone(
        self,
        app_name: str | None = None,
        default_sender: str | None = None,
        default_signer: TransactionSigner | None = None,
        approval_source_map: SourceMap | None = None,
        clear_source_map: SourceMap | None = None,
    ) -> "HelloWorldClient":
        return HelloWorldClient(
            self.app_client.clone(
                app_name=app_name,
                default_sender=default_sender,
                default_signer=default_signer,
                approval_source_map=approval_source_map,
                clear_source_map=clear_source_map,
            )
        )

    def new_group(self) -> "HelloWorldComposer":
        return HelloWorldComposer(self)

    @typing.overload
    def decode_return_value(
        self,
        method: typing.Literal["hello(string)string"],
        return_value: algokit_utils.ABIReturn | None
    ) -> str | None: ...
    @typing.overload
    def decode_return_value(
        self,
        method: typing.Literal["hello_world_check(string)void"],
        return_value: algokit_utils.ABIReturn | None
    ) -> None: ...
    @typing.overload
    def decode_return_value(
        self,
        method: str,
        return_value: algokit_utils.ABIReturn | None
    ) -> algokit_utils.ABIValue | algokit_utils.ABIStruct | None: ...

    def decode_return_value(
        self,
        method: str,
        return_value: algokit_utils.ABIReturn | None
    ) -> algokit_utils.ABIValue | algokit_utils.ABIStruct | None | str:
        """Decode ABI return value for the given method."""
        if return_value is None:
            return None
    
        return return_value.value


class HelloWorldComposer:
    """Composer for creating transaction groups for HelloWorld contract calls"""

    def __init__(self, client: "HelloWorldClient"):
        self.client = client
        self._composer = client.algorand.new_group()

    def hello(
        self,
        args: tuple[str] | HelloArgs,
        params: algokit_utils.CommonAppCallParams | None = None
    ) -> "HelloWorldComposer":
        self._composer.add_app_call_method_call(
            self.client.params.hello(
                args=args,
                params=params,
            )
        )
        return self

    def hello_world_check(
        self,
        args: tuple[str] | HelloWorldCheckArgs,
        params: algokit_utils.CommonAppCallParams | None = None
    ) -> "HelloWorldComposer":
        self._composer.add_app_call_method_call(
            self.client.params.hello_world_check(
                args=args,
                params=params,
            )
        )
        return self

    def clear_state(
        self,
        *,
        args: list[bytes] | None = None,
        params: algokit_utils.CommonAppCallParams | None = None,
    ) -> "HelloWorldComposer":
        params=params or algokit_utils.CommonAppCallParams()
        self._composer.add_app_call(
            self.client.params.clear_state(
                _extend(algokit_utils.AppClientBareCallParams, params, args=args)
            )
        )
        return self
    
    def add_transaction(
        self, txn: Transaction, signer: TransactionSigner | None = None
    ) -> "HelloWorldComposer":
        self._composer.add_transaction(txn, signer)
        return self
    
    def composer(self) -> algokit_utils.TransactionComposer:
        return self._composer
    
    def simulate(
        self,
        allow_more_logs: bool | None = None,
        allow_empty_signatures: bool | None = None,
        allow_unnamed_resources: bool | None = None,
        extra_opcode_budget: int | None = None,
        exec_trace_config: SimulateTraceConfig | None = None,
        simulation_round: int | None = None,
        skip_signatures: bool = False,
    ) -> algokit_utils.SendAtomicTransactionComposerResults:
        return self._composer.simulate(
            allow_more_logs=allow_more_logs,
            allow_empty_signatures=allow_empty_signatures,
            allow_unnamed_resources=allow_unnamed_resources,
            extra_opcode_budget=extra_opcode_budget,
            exec_trace_config=exec_trace_config,
            simulation_round=simulation_round,
            skip_signatures=skip_signatures,
        )
    
    def send(
        self,
        send_params: algokit_utils.SendParams | None = None
    ) -> algokit_utils.SendAtomicTransactionComposerResults:
        return self._composer.send(send_params)


_T = typing.TypeVar("_T")
def _extend(
    new_type: type[_T], base_instance: typing.Any, **changes: object
) -> _T:
    """Creates a new type from an existing object and additional fields"""
    old_type_fields = {f.name : f for f in dataclasses.fields(base_instance)}
    new_type_fields = dataclasses.fields(new_type) # type: ignore[arg-type]
    for field in new_type_fields:
        if not field.init:
            continue
        attr_name = field.name
        if attr_name not in changes and attr_name in old_type_fields:
            changes[attr_name] = getattr(base_instance, attr_name)
    return new_type(**changes)



def _unpack_args(args: object | tuple | None) -> tuple | None:
    if dataclasses.is_dataclass(args):
        return tuple(getattr(args, f.name) for f in dataclasses.fields(args))
    elif isinstance(args, tuple | None):
        return args
    else:
        raise TypeError("unsupported argument type")

_APP_SPEC_JSON = r"""{"arcs": [], "bareActions": {"call": ["DeleteApplication", "UpdateApplication"], "create": ["NoOp"]}, "methods": [{"actions": {"call": ["NoOp"], "create": []}, "args": [{"type": "string", "name": "name"}], "name": "hello", "returns": {"type": "string"}, "events": []}, {"actions": {"call": ["NoOp"], "create": []}, "args": [{"type": "string", "name": "name"}], "name": "hello_world_check", "returns": {"type": "void"}, "events": []}], "name": "HelloWorld", "state": {"keys": {"box": {}, "global": {}, "local": {}}, "maps": {"box": {}, "global": {}, "local": {}}, "schema": {"global": {"bytes": 0, "ints": 0}, "local": {"bytes": 0, "ints": 0}}}, "structs": {}}"""

_STRUCT_NAME_TO_TYPE: dict[str, type] = {
}

APP_SPEC = arc56.Arc56Contract.from_json(
    _APP_SPEC_JSON,
    lambda s: _STRUCT_NAME_TO_TYPE[s.struct_name],
)
